# zsh configuration

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle :compinstall filename '/home/digitalphoton/.zshrc'

autoload -Uz compinit
autoload -Uz add-zsh-hook

# Setting window title on every new prompt
function xterm_title_precmd () {
  print -Pn '\e]2;%1~ %(!.#.$) - zsh \a'
}
if [[ "$TERM" == (screen*|xterm*|rxvt*) ]]; then
  add-zsh-hook -Uz precmd xterm_title_precmd
fi

# Prompt variable
PROMPT='%B%F{red}%n%f%b@%B%F{blue}%m%f%b:%B%F{green}%0~%f%b 
%(?.%?.%F{yellow}%?%f) %(!.%F{yellow}#%f.$) '

compinit

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

setopt appendhistory notify
unsetopt autocd extendedglob

# Vi mode
bindkey -v

# Set default editor to neovim
export EDITOR=/usr/bin/nvim

# Set MPD host
export MPD_HOST=batatasueca@localhost

# Aliases
alias ls='exa'
alias la='ls -a'
alias ll='ls -lh --time-style long-iso --git'
alias cat='bat'

# Colorscheme

# Black
export COLOR0=#303030
export COLOR8=#5d5d5d
# Red
export COLOR1=#e1321a
export COLOR9=#ff361e
# Green
export COLOR2=#6ab017
export COLOR10=#7bc91f
# Yellow
export COLOR3=#ffc005
export COLOR11=#ffd00a
# Blue
export COLOR4=#004f9e
export COLOR12=#0071ff
# Magenta
export COLOR5=#ec0048
export COLOR13=#ff1d62
# Cyan
export COLOR6=#2aa7e7
export COLOR14=#4bb8fd
# White
export COLOR7=#c5c8c6
export COLOR15=#f2f2f2


eval `keychain --agents ssh,gpg --eval --quiet --noask ~/.ssh/id_rsa ~/.gnupg/pubkey`

eval $(thefuck --alias fuck)
